Controllers/UserProfile/UserProfileController.cs
using E_Retalling_Portal.Models;
using E_Retalling_Portal.Models.Enums;
using E_Retalling_Portal.Models.Query;
using E_Retalling_Portal.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using MimeKit;
using MailKit.Net.Smtp;
using MailKit;
using MailKit.Security;
using static System.Net.Mime.MediaTypeNames;
using Newtonsoft.Json;

namespace E_Retalling_Portal.Controllers.UserProfile
{
    public class UserProfileController : Controller
    {
        private GHNService ghNService;

        public IActionResult ViewProfile()
        {
            using (var context = new Context())
            {
                int? accountId = (int)HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());
                Account account = context.Accounts.GetAccountByAccountId(accountId.Value).FirstOrDefault();
                int userId = account.userId;

                User user = context.Users.GetUserByUserIdInAccount(userId).FirstOrDefault();

                
                ViewBag.User = user;
            
                ViewBag.Account = account;



                return View();
            }
        }

        [HttpPost]
        public IActionResult ChangePassword(string currentPassword, string newPassword, string confirmPassword)
        {
            using (var context = new Context())
            {
                int? accountId = (int)HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());

                Account account = context.Accounts.GetAccountByAccountId(accountId.Value).FirstOrDefault();


                if (account.password != currentPassword)
                {
                    TempData["ErrorMessage"] = "The current password is incorrect.";
                    return RedirectToAction("ViewProfile");
                }

                if (newPassword != confirmPassword)
                {
                    TempData["ErrorMessage"] = "The new password and confirmation do not match.";
                    return RedirectToAction("ViewProfile");
                }

                account.password = newPassword;
                context.SaveChanges();

                TempData["SuccessMessage"] = "The password has been changed successfully.";
                return RedirectToAction("ViewProfile");
            }
        }

        [HttpPost]
        public IActionResult Update(User user)
        {
            using (var context = new Context())
            {

                int? accountId = (int)HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());
                Account account = context.Accounts.GetAccountByAccountId(accountId.Value).FirstOrDefault();

                User newUser = context.Users.GetUserByUserIdInAccount(account.userId).FirstOrDefault();

                User testUser = context.Users.GetValidUserData(user.email, user.phoneNumber, newUser.id).FirstOrDefault();

                if (testUser != null)
                {
                    newUser.displayName = user.displayName;
                    newUser.birthday = user.birthday;
                    newUser.gender = user.gender;
                    newUser.firstName = user.firstName;
                    newUser.lastName = user.lastName;
                    newUser.province = user.province;
                    newUser.district = user.district;
                    newUser.ward = user.ward;
                    newUser.address = user.address;
                    if (testUser.email == user.email)
                    {
                        TempData["ErrorEmail"] = "Email is already been registered";
                    }

                    if (testUser.phoneNumber == user.phoneNumber)
                    {
                        TempData["ErrorPhone"] = "PhoneNumber is already registered.";
                    }
                    if(testUser.email != user.email && testUser.phoneNumber != user.phoneNumber)
                    {
                        newUser.email = user.email;
                        newUser.phoneNumber = user.phoneNumber;
                    }
                    context.SaveChanges();
                    return RedirectToAction("ViewProfile");
                }
                else
                {
                    newUser.displayName = user.displayName;
                    newUser.phoneNumber = user.phoneNumber;
                    newUser.birthday = user.birthday;
                    newUser.gender = user.gender;
                    newUser.firstName = user.firstName;
                    newUser.lastName = user.lastName;
                    newUser.province = user.province;
                    newUser.district = user.district;
                    newUser.ward = user.ward;
                    newUser.address = user.address;
                    newUser.province = user.province;
                    newUser.district = user.district;
                    newUser.ward = user.ward;
                    if (newUser.email != user.email)
                    {
                        newUser.email = user.email;
                        HttpContext.Session.SetString(SessionKeys.UserToUpdate.ToString(), JsonConvert.SerializeObject(user));
                        return RedirectToAction("SendOTP", new { emailTo = user.email });
                    }
                    context.SaveChanges();
                    TempData["UpdateMessage"] = "Updated Successfully!";
                    return RedirectToAction("ViewProfile");
                }
                 
                
            }

        }

		[HttpPost]
		public IActionResult VerifyOTP(string enteredOtp)
		{
			var storedOtp = HttpContext.Session.GetString(SessionKeys.Otp.ToString());
			var expirationString = HttpContext.Session.GetString(SessionKeys.OtpExpiration.ToString());

			DateTime expirationTime;
			if (DateTime.TryParse(expirationString, out expirationTime))
			{
				ViewBag.ExpirationTime = expirationTime.ToString();
				if (DateTime.UtcNow <= expirationTime)
				{
					if (storedOtp == enteredOtp)
					{
						HttpContext.Session.Remove(SessionKeys.Otp.ToString());
						HttpContext.Session.Remove(SessionKeys.OtpExpiration.ToString());
						var userJson = HttpContext.Session.GetString(SessionKeys.UserToUpdate.ToString());
						if (userJson != null)
                        {
                            User userToUpdate = JsonConvert.DeserializeObject<User>(userJson);
                            using (var context = new Context())
                            {
                                int? accountId = (int)HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());
                                int userId = context.Accounts.GetUserIdByAccountId(accountId.Value);
                                User newUser = context.Users.GetUserByUserIdInAccount(userId).FirstOrDefault();

                                newUser.displayName = userToUpdate.displayName;
                                newUser.email = userToUpdate.email;
                                newUser.phoneNumber = userToUpdate.phoneNumber;
                                newUser.birthday = userToUpdate.birthday;
                                newUser.gender = userToUpdate.gender;
                                newUser.firstName = userToUpdate.firstName;
                                newUser.lastName = userToUpdate.lastName;
                                newUser.address = userToUpdate.address;
                                newUser.province = userToUpdate.province;
                                newUser.district = userToUpdate.district;
                                newUser.ward = userToUpdate.ward;
                                context.SaveChanges(); 
                            }

                            TempData["UpdateMessage"] = "Updated Successfully!";
                            return RedirectToAction("ViewProfile");
                        }
					}
					else
					{
						ViewBag.OtpError = "Invalid OTP. Please try again!";
						return View("OTPReceive");
					}
				}
				else
				{
					ViewBag.OtpError = "Your OTP has expired. Please request a new one!";
					HttpContext.Session.Remove(SessionKeys.Otp.ToString());
					HttpContext.Session.Remove(SessionKeys.OtpExpiration.ToString());
					return View("OTPReceive");
				}
			}

			return View();
		}

		public IActionResult SendOTP(string emailTo)
		{
			HttpContext.Session.SetString(SessionKeys.Email.ToString(), emailTo);
			var email = new MimeMessage();

			var otp = OTPService.GenerateOTP();
			HttpContext.Session.SetString(SessionKeys.Otp.ToString(), otp);

			DateTime expirationTime = DateTime.UtcNow.AddMinutes(1);
			HttpContext.Session.SetString(SessionKeys.OtpExpiration.ToString(), expirationTime.ToString());

			email.From.Add(new MailboxAddress("E-Retailing-Portal", "quya1k48@gmail.com"));
			email.To.Add(new MailboxAddress("", emailTo));

			email.Subject = "Verify OTP To Register";
			email.Body = new TextPart(MimeKit.Text.TextFormat.Html)
			{
				Text = $@"
        <html>
        <body>
            <p>We have received a request to update information of your account. To confirm this request, please enter the OTP below:</p>
            <h2 style='color: blue;'>{otp}</h2>
            <p>This OTP will expire in 1 minutes. If you did not request a verification, you can safely ignore this email.</p>
            <p>Thank you for using our service!</p>
            <p>Best regards,<br>[E-Retailing-Portal]<br>[Contact Information: 0862003064]</p>
        </body>
        </html>"
			};

			using (var smtp = new SmtpClient())
			{
				smtp.Connect("smtp.gmail.com", 587, false);
				smtp.Authenticate("quya1k48@gmail.com", "dwuueitkzbynxhhk");
				smtp.Send(email);
				smtp.Disconnect(true);
			}

			return View("OTPReceive");
		}

	}
}

Views/UserProfile/OTPReceive.cshtml
@{
	Layout = null;

	var expirationString = Context.Session.GetString(SessionKeys.OtpExpiration.ToString());
	var email = Context.Session.GetString(SessionKeys.Email.ToString());
	DateTime expirationTime;
	if (!DateTime.TryParse(expirationString, out expirationTime))
	{
		expirationTime = DateTime.Now.AddMinutes(1);
	}
}
<style>
	.btn {
		color: dimgray;
		background-color: white;
		border: none;
		font-size: 16px;
		font-weight: 800;
		cursor: pointer;
	}

	body {
		font-family: 'Arial', sans-serif;
		background-color: #f8f9fa;
		margin: 0;
	}

	.height-100 {
		height: 100vh;
		display: flex;
		justify-content: center;
		align-items: center;
	}

	.card {
		width: 400px;
		border: none;
		height: auto;
		padding: 20px;
		box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.1);
		border-radius: 8px;
		background-color: #ffffff;
		z-index: 1;
		text-align: center;
	}

		.card h6 {
			color: #dc3545;
			font-size: 20px;
			margin-bottom: 15px;
		}

	.inputs {
		margin: 20px 0;
	}


		.inputs input:focus {
			outline: none;
			border-color: #28a745;
			box-shadow: 0 0 5px rgba(40, 167, 69, 0.5);
		}

	.validate {
		border-radius: 5px;
		height: 60px;
		padding: 0 20px;
		background-color: #dc3545;
		border: none;
		color: white;
		font-size: 18px;
		transition: background-color 0.3s ease;
	}

		.validate:hover {
			background-color: #c82333;
		}

	.inputs input {
		width: 160px;
		height: 60px;
		font-size: 24px;
		text-align: center;
		border: 2px solid #dc3545;
		border-radius: 5px;
	}

	#countdown {
		font-weight: bold;
		margin-top: 15px;
	}

	a {
		color: #007bff;
		text-decoration: none;
		display: block;
		margin-top: 15px;
	}

		a:hover {
			text-decoration: underline;
		}
</style>
<div class="container height-100">
	<div class="card">
		<h6>Please enter the one-time password <br> to verify your account</h6>
		<div>
			<span>A code has been sent to</span> <small>@email</small>
		</div>

		<div id="countdown" class="mt-2 text-danger"></div>

		<form id="otpForm" asp-controller="UserProfile" asp-action="VerifyOTP" method="post">
			<div class="inputs mt-2">
				<input type="text" name="enteredOtp" required maxlength="6" />
			</div>
			<div class="mt-4">
				<button class="btn validate">Validate</button>
			</div><br />
			<div id="otp-error" class="alert alert-danger">@ViewBag.OtpError</div>
		</form>

		<div class="text-center my-3">
			<form action="@Url.Action("SendOTP", "UserProfile")" style="display: inline;">
				<input type="hidden" name="emailTo" value="@email" />
				<button type="submit" class="btn btn-primary btn-lg">
					Resend OTP
				</button>
			</form>
		</div>
	</div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
	var expirationTime = new Date('@expirationTime.ToString("yyyy-MM-ddTHH:mm:ssZ")');

	function updateCountdown() {
		var now = new Date();
		var remainingTime = expirationTime - now;

		if (remainingTime <= 0) {
			document.getElementById("countdown").textContent = "Your OTP has expired. Please request a new one!";
			document.querySelectorAll('#otpForm input').forEach(input => {
				input.disabled = true;
			});
			document.querySelector('#otpForm button').disabled = true;
			return;
		}

		var m = Math.floor((remainingTime % (1000 * 60 * 60)) / (1000 * 60));
		var s = Math.floor((remainingTime % (1000 * 60)) / 1000);
		m = m < 10 ? "0" + m : m;
		s = s < 10 ? "0" + s : s;

		document.getElementById("countdown").innerHTML = `Time left: ${m} : ${s}`;
		setTimeout(updateCountdown, 1000);
	}

	updateCountdown();
</script>

Views/UserProfile/VerifyOTP.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    Layout = null;
}
<link href="~/kit/css/ghost.css" rel="stylesheet" />
<div class="box">
    <div class="box__ghost">
        <div class="symbol"></div>
        <div class="symbol"></div>
        <div class="symbol"></div>
        <div class="symbol"></div>
        <div class="symbol"></div>
        <div class="symbol"></div>

        <div class="box__ghost-container">
            <div class="box__ghost-eyes">
                <div class="box__eye-left"></div>
                <div class="box__eye-right"></div>
            </div>
            <div class="box__ghost-bottom">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
        <div class="box__ghost-shadow"></div>
    </div>

    <div class="box__description">
        <div class="box__description-container">
            <div class="box__description-title">Whoops!</div>
            <div class="box__description-text">An error occurred while processing your request. Please go back to homepage</div>
        </div>

        <a href="@Url.Action("Index", "Home")" target="_blank" class="box__button">Go back to homepage</a>

    </div>
</div>